builds:
  - id: telemetry
    main: ./cmd/telemetry
    flags:
      - -trimpath
    ldflags:
      - -X main.version={{.Env.VERSION}}
      - -s -w  # strip symbols (make the binary smaller)
      - -extldflags "-static"
