config:
  default: true
  line-length: false

globs:
  - "**/*.{md,markdown}"

ignores:
  - "CHANGELOG.md"
  - ".gitlab/issue_templates/**"
  - "charts/telemetry/charts/postgresql/**"
  - "docs/cli/**"
  - "docs/apis/**"
  - "internal/webapp/assets/.downloads/**"
  - "internal/webapp/assets/static/libs/**"
