# Project configuration file for ACT3 Project Tool
kind: Project
apiVersion: project.act3-ace.io/v1beta1

# Project metadata used in Blueprints
meta:
  name: telemetry
  title: Telemetry
  description: ACE Data Tool Telemetry Server
  repository: https://gitlab.com/act3-ai/data/telemetry.git
  authors:
    - name: Kyle M. Tarplee
      email: kyle.tarplee@udri.udayton.edu

# List of Blueprints configured for this project
blueprints:
  - ref: https://git.act3-ace.com/devsecops/project-templates/act3-base.git@v0.0.7
    inputs:
      defaultAssignee: ljones
      envPrefix: ACE_TELEMETRY # Prefix for configuration environment variables
      executableName: telemetry # Name of the CLI's executable
      groupName: config.telemetry.act3-ace.io # API group name for your project
      modulePath: gitlab.com/act3-ai/asce/data/telemetry # Go module path for the project

# Edit configuration interactively:
#   Edit metadata:         act3-pt edit
#   Edit CI config:        act3-pt ci edit
#   Edit Blueprint config: act3-pt blueprint edit
# Manage Blueprints:
#   Add Blueprints:  act3-pt blueprint add
#   Update versions: act3-pt blueprint update
# Use CI/CD:
#   Set up CI/CD:  act3-pt ci setup
#   Run pipelines: act3-pt ci run
