apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry.fullname" . }}
  labels:
    {{- include "telemetry.labels" . | nindent 4 }}
data:
  config.yaml: |-
    webapp:
      {{- toYaml .Values.webapp | nindent 6 }}

