apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetry.fullname" . }}
  labels:
    {{- include "telemetry.labels" . | nindent 4 }}
  annotations:
    logs.act3-ace.io/jq: {{ .Files.Get "log.jq" | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "telemetry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        logs.act3-ace.io/jq: {{ .Files.Get "log.jq" | quote }}
      labels:
        {{- include "telemetry.selectorLabels" . | nindent 8 }}
        {{- with .Values.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "telemetry.fullname" . }}
        - name: tmp-dir
          emptyDir: {}
      serviceAccountName: {{ include "telemetry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - serve
            - --config=/etc/ace/telemetry/config.yaml
          env:
            - name: ACE_TELEMETRY_LISTEN
              value: ":8100"
            - name: ACE_TELEMETRY_VERBOSITY
              value: {{ .Values.verbosity | quote }}
          {{- range $key, $value := .Values.environment }}
            - name: {{ $key | snakecase | upper }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if and .Values.db.existingSecret.name .Values.db.existingSecret.key }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret.name }}
                  key: {{ .Values.db.existingSecret.key }}                
          {{- end }}
          {{- if .Values.db.dsn }}
            - name: ACE_TELEMETRY_DSN
              value: {{ .Values.db.dsn }}
          {{- end }}
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          volumeMounts:
            - name: config
              mountPath: /etc/ace/telemetry/
              readOnly: true
            - name: tmp-dir
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 8100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
