{{- if .Values.prometheus.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "telemetry.fullname" . }}
  labels:
    {{- include "telemetry.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      {{- include "telemetry.selectorLabels" . | nindent 6 }}
{{- end }}
