name: dagger
run-name: ${{ github.actor }} is testing with dagger 🗡️
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dagger Engine
        uses: dagger/dagger-for-github@8.0.0
    
      - name: Prepare
        run: |
            make deps
            
      - name: Lint
        run: dagger call lint all
        continue-on-error: true

      - name: Test
        run: dagger call test all
        continue-on-error: true
    
      - name: VulnCheck
        run: dagger call vuln-check
        continue-on-error: true

      - name: Build
        run: dagger call build-platforms
        continue-on-error: true
